### ISSUE TITLE
Integrate JS linter

### ISSUE THREAD

**Issue by frostiq** [rootprojectco/backend#15]
The linter must ensure that:

- Arrow functions must be used instead of regular functions, where possible
- `let` must be used instead of `var`, where possible
- `;` must be omitted, where possible
- any other reasonable rule

**Comment by Quazia** [comment]
I've started on this using ESlint, if anyone has a reason not to use ESlint let me know. I added in all the rules mentioned as well as the standard rules. I went with 4 spaces so that it's in keeping with solidity indentations.

**Comment by frostiq** [comment]
I'm completely ok with ESlinter
Cool, will wait for a PR from you :)
